name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Commit build to main
        if: github.event_name == 'push'
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add public
          git commit -m "Build assets for production" || exit 0
          git push
      - name: Commit build to pull request
        if: github.event_name == 'pull_request'
        run: |
          git pull origin $GITHUB_HEAD_REF
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add public
          git commit -m "Build assets for pull request" || exit 0
          git push origin HEAD:refs/heads/$GITHUB_HEAD_REF

  style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Fix PHP code style issues
        uses: aglipanci/laravel-pint-action@1.0.0
